Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -13,7 +13,7 @@ on:
 
 jobs:
   build:
-    runs-on: windows-latest  # Змінюємо з ubuntu-latest на windows-latest
+    runs-on: windows-latest  # Changed from ubuntu-latest to windows-latest
 
     steps:
     - name: Checkout репозиторію
@@ -22,7 +22,7 @@ jobs:
     - name: Встановлення .NET Framework Developer Pack
       run: |
         choco install dotnetfx -y
-        choco install dotnet-4.7.2-devpack -y
+        choco install dotnet-4.7.2-devpack -y || echo "dotnet-4.7.2-devpack installation failed, continue with the build."
 
     - name: Встановлення .NET
       uses: actions/setup-dotnet@v4
@@ -37,3 +37,4 @@ jobs:
 
     - name: Запуск тестів
       run: dotnet test --no-build --verbosity normal
+
